### ISSUE TITLE
Filters on arcgispro generated tiles

### ISSUE THREAD

**Issue by mikeri1000** [gbochenek/vector-tile-demo-js#1]
Hi, thanks for posting this repo, I first saw the demo at the ESRI 2017 UC and it's been a big help in understanding vector tiles. 

This isn't an issue with the actual demo. but relates to the the vector tiles you use. Applying the filter based on the origin or destination of the flights, means that the tiles have that data baked in, probably from an attribute table? Even though those attributes aren't immediately visible in any way. 

I've been trying to use my own hosted tiles that I published on Portal through ArcGIS Pro. I am able to load the tiles, change the paint settings etc.. but am unable to filter them based on any of the attribute fields in the original layer. It seems like filtering them filters everything. So I'm assuming the tiles don't have the fields I'm looking for. Do you have any tips on publishing tiles from Pro that can be filtered? Should I be publishing tiles some other way? 

Thanks and I apologize if I'm posting a query like this in the wrong place.

**Comment by tfauvell** [comment]
I can field your question (and close this issue). The vector tile service used by this application was created with additional fields (keys) and attributes (values) cooked into the tiles (pbf's) to facilitate the in app filtering. I'll be posting a video online shortly to demo this functionality. I'll be sure to post a link back here as well. In a nutshell: ArcGIS Pro only cooks the bare minimum attributes into the vector tiles (label expression results, symbol class id, etc...). You can "highlight" a field from the featureclass attribute table to force the cooker to encode that field (key) and the feature attributes (values) into the tiles. 

How to "highlight" a field: 
1.  Open the layer's attribute table, and then open the field view
- with the attribute table tab selected, the "Table" context menu should appear in the ribbon. Click View, then click the "Fields" button (in the Field group, next to Add, Delete, Sort). The "Fields: <Layer Name>" tab should open.
2. Warning: what you're about to do can adversely affect the tile sizes you create. Tread lightly, and use this feature sparingly.
- Place a check in the "Highlight" column, for the field that you want encoded into your tiles. Take note of the field name, as this is what you'll reference in your style filter.
4. Be sure to click the save button in the ribbon (in the "Changes" ribbon group).

You can now, re-run your create vector tile package job / share web layer (which ever you used). The field you encoded (key) will now be available to filter against.

**Comment by mikeri1000** [comment]
thanks a lot! that worked exactly as expected.
